### PR TITLE
Add headers from quark repo

### PR DESCRIPTION
**Pull request by mjwolf**
Add the headers required for cgo compilation to this repo.

These headers are from `elastic/quark`, and will need to be kept in sync with that in the future. Github releases do not include submodules, so these files must be included in this repo directly for the Go module to build.

### CODE REVIEW

**Comment by haesbaert** [comment]
We should hook this into the CI, when the headers change, they must be updated, can we do this together with the archive files?
Ideally we would also add a check to make sure the headers match, like `diff -su quark.h src/quark.h || die`

**Review by haesbaert — CHANGES_REQUESTED** [review]
I think we will shoot ourselves in the foot if we end up shipping a different header than the one we compiled with, things will break in hard ways to debug. We should hook this into the CI.
We can:
1 - copy the headers out of the submodule
2 - compile the submodule
3 - copy the headers out of the submodule
4 - generate a commit for both the archive files and the headers

1 -> 2 is to make sure we don't screw up the `-I` and end up compiling with the wrong header, so better to copy out before compiling.

What do you think?

**Comment by mjwolf** [comment]
> I think we will shoot ourselves in the foot if we end up shipping a different header than the one we compiled with, things will break in hard ways to debug. We should hook this into the CI. We can: 1 - copy the headers out of the submodule 2 - compile the submodule 3 - copy the headers out of the submodule 4 - generate a commit for both the archive files and the headers
> 
> 1 -> 2 is to make sure we don't screw up the `-I` and end up compiling with the wrong header, so better to copy out before compiling.
> 
> What do you think?

yes, good idea. it should be pretty straightforward to reuse the CI process that keeps .a files up-to-date to do this too

**Comment by mjwolf** [comment]
CI isn't currently set up to build from forks. Closing this PR, I'll reopen another from a branch in this repo

**Pull request closed without merging**
